version: 2.1

jobs:
  manylinux228_aarch64_with_deps-build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
    - checkout
    - run:
        name: Build and push aarch64
        command: |
          docker build -f Dockerfile228 . --build-arg IMAGE=quay.io/pypa/manylinux_2_28_aarch64

workflows:
  version: 2.1
  all_builds:
    jobs:
    - manylinux228_aarch64_with_deps-build
