version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  docker/publish:
    resource_class: arm.medium
    docker-username: ${ DOCKERHUB_USERNAME }
    docker-password: ${ DOCKERHUB_TOKEN }
    image: ${ DOCKERHUB_USERNAME }/manylinux228_aarch64_with_deps
    dockerfile: Dockerfile228
    extra_build_args: --build-arg IMAGE=quay.io/pypa/manylinux_2_28_aarch64
    tags: latest

workflows:
  version: 2.1
  all_builds:
    jobs:
    - docker/publish:
