name: ci

on:
  push:
    branches:
      - "master"

jobs:
  manylinux228_x86_64_with_deps-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile228
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux228_x86_64_with_deps:latest

  manylinux228_aarch64_with_deps-build:
      -
        name: Checkout
        uses: actions/checkout@v3
      # Setup to bulid arm based container since the actions run on x86 machines.
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push arm64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile228
          platforms: linux/arm64
          push: true
          build-args:
            IMAGE: quay.io/pypa/manylinux_2_28_aarch64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux228_aarch64_with_deps:latest
